### ISSUE TITLE
[Not An Issue] [Request] My Own Config

### ISSUE THREAD

**Issue by CreativeCodeCat** [tmccombs/i3-cheat#1]
hello i have my config at [config](https://gitlab.com/TheCynicalLiger/DotFiles/-/raw/master/.config/i3/config) and would like for you to have a look at it and maybe find a way to get your script to work with its formatting that would be awesome also i would like to add custom categories here is what im using at the meantime [show_help](https://gitlab.com/TheCynicalLiger/DotFiles/-/raw/master/.config/i3/scripts/show_help.sh)

thanks in advance
Liger

**Comment by tmccombs** [comment]
https://github.com/tmccombs/i3-cheat/commit/5cdd1af297631fcfd4d9d84694f6eb0b53efb9fb fixes the problem with variable substitution not working in that script.

As for custom categories, I'm not entirely sure what you mean. Looking at your `show_help` script, it looks like it parses a "Description" comment before the binding to display. I'd be open to doing something like that. Or did you have something else in mind?

**Comment by CreativeCodeCat** [comment]
what i'm looking for it to do it is where u have the tabs at the top they will be categories so for example i would have ## Category: Default; above the  Description and it will put it into that tab... hope you understand what i mean :)

Config Example:
![Config Example:](https://i.imgur.com/Bgzh6zZ.png)

Bad Photoshop:
![Config Example:](https://i.imgur.com/qrTJWa6.png)

**Comment by CreativeCodeCat** [comment]
Also on Arch Linux I get this error!
![TypeError: Must be number, not NoneType](https://i.imgur.com/wLcqYuy.png)

and gtk-key-bindings should be -gtk-key-bindings 

```(i3-cheat:88701): Gtk-WARNING **: 15:06:15.329: Theme parsing error: <data>:11:28: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'```

**Comment by tmccombs** [comment]
I fixed the error messages, and created a new issue to track custom categories and descriptions. I think it is a good idea, but I'm not sure what I wan the syntax for that to look like.

**Comment by CreativeCodeCat** [comment]
Ok m8
