### ISSUE TITLE
Custom tabs and descriptions.

### ISSUE THREAD

**Issue by tmccombs** [tmccombs/i3-cheat#2]
Add a way to specify tabs and descriptions of commands using comments.

I definitely think this is a valuable feature. My biggest question is what the syntax for the comments should be. Some ideas:

```
## Category:  Media
## Description: Increase volume
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%
```
(adapted from @TheCynicalLiger's config in #1)

```
## Media:
#* Increase volume
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%
```

```
#! *Media*
#! Increase volume
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%
```

or something else?

**Comment by CreativeCodeCat** [comment]
I do like the bottom syntax as long as I could still do the commands with multi line like I have it now

**Comment by CreativeCodeCat** [comment]
this format could also work as it would stand out more :)
```
##---Media---##
#---Increase volume---#
bindsym XF86AudioRaiseVolume \
     exec pactl set-sink-volume @DEFAULT_SINK@ +5%
```

**Comment by CreativeCodeCat** [comment]
any update on this mate?

**Comment by tmccombs** [comment]
no, I haven't really looked into it more

**Comment by CreativeCodeCat** [comment]
@tmccombs here is my script [keybinds](https://github.com/TheCynicalTeam/DotFiles/blob/master/.config/i3/scripts/keybinds.py) if you need help with how to do it :)

**Comment by CreativeCodeCat** [comment]
[wm-cheat](https://github.com/The-Repo-Club/wm-cheat) here is my version if you wanna check it out
